# Generated by Django 2.1.7 on 2019-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Неделя'), (2, 'Месяц'), (3, 'Квартал'), (4, 'Год')], verbose_name='Период'),
        ),
    ]
