# Generated by Django 2.1.7 on 2019-03-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0002_auto_20190317_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(db_index=True, verbose_name='Крайний срок')),
                ('end_date', models.DateField(blank=True, db_index=True, verbose_name='Дата завершения')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='planer.Documents', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
