# Generated by Django 2.1.7 on 2019-03-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0005_todolist_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
