# Generated by Django 2.1.7 on 2019-03-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0006_todolist_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='Название')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='document',
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=128, verbose_name='Название задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='planer.Category', verbose_name='Категория'),
        ),
    ]
