# Generated by Django 2.1.7 on 2019-03-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0007_auto_20190319_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(db_index=True, default='success', max_length=8, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
