# Generated by Django 2.1.7 on 2019-03-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0009_auto_20190320_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'primary'), (2, 'secondary'), (3, 'success'), (4, 'danger'), (5, 'warning'), (6, 'info'), (7, 'dark'), (8, 'red')], db_index=True, default=2, verbose_name='Цвет'),
        ),
    ]
