# Generated by Django 2.1.7 on 2019-03-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0010_auto_20190320_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'blue'), (2, 'secondary'), (3, 'green'), (4, 'red'), (5, 'darkorange'), (6, 'light-blue'), (7, 'black'), (8, 'indigo'), (9, 'lawngreen'), (10, 'darkviolet'), (11, 'brown')], db_index=True, default=2, verbose_name='Цвет'),
        ),
    ]
