# Generated by Django 2.1.7 on 2019-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0012_auto_20190320_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'blue'), (2, 'black'), (3, 'brown'), (4, 'darkorange'), (5, 'darkviolet'), (6, 'indigo'), (7, 'gray'), (8, 'lightblue'), (9, 'lawngreen'), (10, 'green'), (11, 'gold'), (12, 'red')], db_index=True, default=2, verbose_name='Цвет'),
        ),
    ]
