# Generated by Django 2.1.7 on 2019-03-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0013_auto_20190320_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
