# Generated by Django 2.1.7 on 2019-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0014_delete_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=32, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=32, verbose_name='Имя')),
                ('patronym', models.CharField(max_length=32, null=True, verbose_name='Отчество')),
                ('is_doctor', models.BooleanField(db_index=True, default=True, verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
