# Generated by Django 2.1.7 on 2019-03-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0017_auto_20190324_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
