# Generated by Django 2.1.7 on 2019-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0018_auto_20190324_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Название')),
                ('for_doctor', models.BooleanField(default=True, verbose_name='Для врачей')),
            ],
            options={
                'verbose_name': 'Реферат',
                'verbose_name_plural': 'Рефераты',
            },
        ),
    ]
