# Generated by Django 2.1.7 on 2019-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0019_referats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='is_doctor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='referats',
            name='for_doctor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Для врачей'),
        ),
    ]
