# Generated by Django 2.1.7 on 2019-03-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0020_auto_20190324_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Название (период)')),
                ('first_year', models.PositiveSmallIntegerField(unique=True, verbose_name='Первый год')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитации',
                'ordering': ('first_year',),
            },
        ),
        migrations.CreateModel(
            name='SetReferat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата реферата')),
                ('accredit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planer.Accredits')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planer.Employees')),
                ('referat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planer.Referats')),
            ],
        ),
        migrations.AddField(
            model_name='accredits',
            name='employee',
            field=models.ManyToManyField(related_name='assigned_employee', through='planer.SetReferat', to='planer.Employees'),
        ),
        migrations.AddField(
            model_name='accredits',
            name='referat',
            field=models.ManyToManyField(related_name='assigned_referat', through='planer.SetReferat', to='planer.Referats'),
        ),
        migrations.AlterUniqueTogether(
            name='setreferat',
            unique_together={('referat', 'employee', 'accredit')},
        ),
    ]
