# Generated by Django 2.1.7 on 2019-03-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0021_auto_20190324_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accredits',
            options={'ordering': ('-first_year',), 'verbose_name': 'Аккредитация', 'verbose_name_plural': 'Аккредитации'},
        ),
    ]
