# Generated by Django 2.1.7 on 2019-03-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0023_auto_20190325_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['last_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
